classdef Simulation
% solarcell.Simulation
%
% Value class wrapping the configuration produced by DesignSim.m. Second
% slice of the OOP migration, following the same strangler pattern as
% solarcell.Junction:
%
%   - properties hold every tuning knob DesignSim.m exposes,
%   - toStruct(junction) materialises the legacy struct layout,
%   - DesignSim.m stays in place as the regression oracle,
%   - the snapshot test in tests/SimulationSnapshotTest pins parity.
%
% The class composes with solarcell.Junction rather than inheriting from
% it -- a Simulation is "how to simulate", a Junction is "what to
% simulate", and toStruct(junction) combines the two into the flat struct
% every legacy consumer expects.
%
% Layout of the output struct (matches DesignJunction + DesignSim):
%   .input / .material / .optical.periodic / .phys  -- from Junction
%   .optical.setup      -- RCWA + mesh + display knobs (this class)
%   .electrical.setup   -- DDNewton + tolerances + plot toggles (this class)

    properties
        % --- Optical setup (sim.optical.setup) ------------------------
        optical_toggle      (1,1) double = 1
        parforArg           (1,1) double = inf
        epsmethod           (1,1) double = 2
        iepsmethod          (1,1) double = 2
        Ez_A_or_iE          (1,1) double = 0
        pol                 (1,1) double = 0
        RebuildFields       (1,1) double = 0
        optplot             (1,1) double = 0
        epsplot             (1,1) double = 0
        Eplot               (1,1) double = 0
        Hplot               (1,1) double = 0
        degtheta0           (1,1) double = 0
        degtheta1           (1,1) double = 0
        ntheta              (1,1) double = 1
        nmlambda0           (1,1) double = 301
        nmlambda1           (1,1) double = 1400
        nlambda             (1,1) double = 1 + floor((1400 - 301) / 10)
        Nx                  (1,1) double = 100
        nslices             (1,:) double = [1, 1, 1, 5, 15, 10, 1, 5, 1]
        CheckNtConvergence  (1,1) double = 0
        Nttol               (1,1) double = 1e9
        Nttol_lower         (1,1) double = 1e-6
        minNt               (1,1) double = 10
        maxNt               (1,1) double = 12
        nosuccreq           (1,1) double = 2
        faillimit           (1,1) double = 10
        ptol                (1,1) double = 0.1

        % --- Electrical setup (sim.electrical.setup) ------------------
        electrical_toggle   (1,1) double = 1
        pdeg                (1,1) double = 7
        VdV                 (1,1) double = 0.01
        rerunbackward       (1,1) double = 0
        elec_nslices        (1,:) double = [1, 1, 1, 5, 15, 10, 1, 5, 1]
        nmdz                (1,1) double = 2
        nx_sec              (1,:) double = [5, 15, 10]
        meshfn              char         = '1'
        upwind              (1,1) double = 1
        tensor              (1,1) double = 0
        t_1                 (1,1) double = 1e-6
        t_2                 (1,1) double = 1e3
        quadtoggle          (1,1) double = 1
        intdeg              (1,1) double = 12
        SolverSteps         (1,1) double = 0
        plotsolve           (1,1) double = 0
        ExportSCdetails     (1,1) double = 0
        nx_plot             (1,1) double = 2
        plot_densities      (1,1) double = 1
        plot_fields         (1,1) double = 1
        plot_levels         (1,1) double = 1
        plot_currents       (1,1) double = 1
        plot_U              (1,1) double = 1
        plot_tau            (1,1) double = 1
        dampmin             (1,1) double = 1e-9
        damprelax           (1,1) double = 1.3
        trydamping          (1,1) double = 40
        dampingincrease     (1,1) double = 5
        mesh_increase       (1,1) double = 1.5
        refine_on_negative  (1,1) double = 1
        refine_on_Jnoise    (1,1) double = 1
        maxJnoiserefinefrac (1,1) double = 0.2
        refine_always       (1,1) double = 0
        maxloop             (1,1) double = 40
        maxpdeg             (1,1) double = 12
        maxtime             (1,1) double = 60 * 60
        mindV               (1,1) double = 1e-6
        reltol              (1,1) double = 1e-2
        abstol              (1,1) double = 1e-4
        warn                (1,1) double = 1
        Jtol                (1,1) double = 0.4
        forcepositive       (1,1) double = 0
        test_J              (1,1) double = 0
        PVrefinemax         (1,1) double = 100
        PVtol               (1,1) double = 1e-3
    end

    methods
        function sim = toStruct(obj, junction)
            % Materialise the legacy struct expected by DesignSim's
            % downstream consumers. `junction` may be a solarcell.Junction
            % or the raw struct returned by DesignJunction().
            if isa(junction, 'solarcell.Junction')
                sim = junction.toStruct();
            else
                sim = junction;
            end

            sim.optical.setup    = obj.opticalSetupStruct();
            sim.electrical.setup = obj.electricalSetupStruct();

            % Pad nslices if shorter than the section count. Verbatim from
            % DesignSim.m: legacy fix-up rather than a hard validation, so
            % preserve it for snapshot parity.
            diff = sim.material.nsec - length(sim.optical.setup.nslices);
            if diff > 0
                sim.optical.setup.nslices = [sim.optical.setup.nslices, ones(1, diff)];
            end

            % Nt starts at minNt; counter starts at zero. Both deterministic.
            sim.optical.setup.Nt          = sim.optical.setup.minNt;
            sim.electrical.setup.counter  = 0;

            % Runtime markers. Non-deterministic by construction -- start_time
            % is a monotonic tick captured "now"; the snapshot test strips
            % these before comparing. Kept here for parity with DesignSim so
            % downstream code that reads them keeps working unchanged.
            sim.electrical.setup.start_time = tic;
            sim.electrical.setup.total_time = toc(sim.electrical.setup.start_time);
        end
    end

    methods (Access = private)
        function s = opticalSetupStruct(obj)
            % Order mirrors DesignSim.m's optical.setup assignment so that
            % field ordering matches (isequaln ignores order, but matching
            % keeps diffs minimal during the migration).
            s = struct( ...
                'optical_toggle',     obj.optical_toggle, ...
                'parforArg',          obj.parforArg, ...
                'epsmethod',          obj.epsmethod, ...
                'iepsmethod',         obj.iepsmethod, ...
                'Ez_A_or_iE',         obj.Ez_A_or_iE, ...
                'pol',                obj.pol, ...
                'RebuildFields',      obj.RebuildFields, ...
                'optplot',            obj.optplot, ...
                'epsplot',            obj.epsplot, ...
                'Eplot',              obj.Eplot, ...
                'Hplot',              obj.Hplot, ...
                'degtheta0',          obj.degtheta0, ...
                'degtheta1',          obj.degtheta1, ...
                'ntheta',             obj.ntheta, ...
                'nmlambda0',          obj.nmlambda0, ...
                'nmlambda1',          obj.nmlambda1, ...
                'nlambda',            obj.nlambda, ...
                'Nx',                 obj.Nx, ...
                'nslices',            obj.nslices, ...
                'CheckNtConvergence', obj.CheckNtConvergence, ...
                'Nttol',              obj.Nttol, ...
                'Nttol_lower',        obj.Nttol_lower, ...
                'minNt',              obj.minNt, ...
                'maxNt',              obj.maxNt, ...
                'nosuccreq',          obj.nosuccreq, ...
                'faillimit',          obj.faillimit, ...
                'ptol',               obj.ptol);
        end

        function s = electricalSetupStruct(obj)
            % `nslices` lives under both optical.setup and electrical.setup
            % in the legacy struct (different defaults are possible in
            % principle even though the values match today). The property
            % is exposed as `elec_nslices` here to avoid colliding with the
            % optical one, and projected back to `nslices` on output.
            s = struct( ...
                'electrical_toggle',   obj.electrical_toggle, ...
                'pdeg',                obj.pdeg, ...
                'VdV',                 obj.VdV, ...
                'rerunbackward',       obj.rerunbackward, ...
                'nslices',             obj.elec_nslices, ...
                'nmdz',                obj.nmdz, ...
                'nx_sec',              obj.nx_sec, ...
                'meshfn',              obj.meshfn, ...
                'upwind',              obj.upwind, ...
                'tensor',              obj.tensor, ...
                't_1',                 obj.t_1, ...
                't_2',                 obj.t_2, ...
                'quadtoggle',          obj.quadtoggle, ...
                'intdeg',              obj.intdeg, ...
                'SolverSteps',         obj.SolverSteps, ...
                'plotsolve',           obj.plotsolve, ...
                'ExportSCdetails',     obj.ExportSCdetails, ...
                'nx_plot',             obj.nx_plot, ...
                'plot_densities',      obj.plot_densities, ...
                'plot_fields',         obj.plot_fields, ...
                'plot_levels',         obj.plot_levels, ...
                'plot_currents',       obj.plot_currents, ...
                'plot_U',              obj.plot_U, ...
                'plot_tau',            obj.plot_tau, ...
                'dampmin',             obj.dampmin, ...
                'damprelax',           obj.damprelax, ...
                'trydamping',          obj.trydamping, ...
                'dampingincrease',     obj.dampingincrease, ...
                'mesh_increase',       obj.mesh_increase, ...
                'refine_on_negative',  obj.refine_on_negative, ...
                'refine_on_Jnoise',    obj.refine_on_Jnoise, ...
                'maxJnoiserefinefrac', obj.maxJnoiserefinefrac, ...
                'refine_always',       obj.refine_always, ...
                'maxloop',             obj.maxloop, ...
                'maxpdeg',             obj.maxpdeg, ...
                'maxtime',             obj.maxtime, ...
                'mindV',               obj.mindV, ...
                'reltol',              obj.reltol, ...
                'abstol',              obj.abstol, ...
                'warn',                obj.warn, ...
                'Jtol',                obj.Jtol, ...
                'forcepositive',       obj.forcepositive, ...
                'test_J',              obj.test_J, ...
                'PVrefinemax',         obj.PVrefinemax, ...
                'PVtol',               obj.PVtol);
        end
    end
end
